M48
; DRILL file {KiCad 9.0.7} date 2026-03-23T10:39:09+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-23T10:39:09+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X156.28Y-118.565
X162.06Y-118.565
T2
X130.45Y-119.85
X138.45Y-119.85
T3
X172.4Y-114.22
X183.83Y-114.22
M30
